version: "3.8"

services:
  app:
    build: .
    ports:
      - "3002:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sensordb
    ports:
      - "5432:5432"

  adminer:
    container_name: sensor_adminer
    image: adminer
    restart: always
    ports:
      - "8086:8080"
